#!/bin/sh

# $Id: buildall-without-xml,v 1.7 2007/06/05 17:47:56 misha Exp $

install_directory=$HOME/parser3install
sendmail_command="/usr/sbin/sendmail -i -t -f postmaster"

echo "buildall-without-xml"
echo "Script author: Alexander Petrosian <paf@design.ru> (http://paf.design.ru)"
echo
echo "Building..."

parser3_directory=`pwd`
cd ..
project_directory=`pwd`
mkdir src >/dev/null 2>&1

if test ! -f "$project_directory/gc/lib/libgc.a"; then
  cd $project_directory/src
  libgc="gc6.8"
  if test ! -f "$libgc.tar.gz"; then
    echo "Downloading libgc [1 lib of 1]..."
    wget -c http://www.hpl.hp.com/personal/Hans_Boehm/gc/gc_source/$libgc.tar.gz
  fi
  echo "Unpacking gc..."
  rm -rf $libgc
  gunzip -c $libgc.tar.gz | tar vxf - >/dev/null
  cd $libgc
  echo "Configuring libgc..."
  CPPFLAGS="-DUSE_LIBC_PRIVATES -DUSE_MMAP -DUSE_MUNMAP" \
  ./configure --prefix=$project_directory/gc --disable-threads --disable-shared --silent
  echo "Building libgc..."
  make
  make install
#  rm -rf $libgc
fi


cd $parser3_directory

if test ! -f "Makefile"; then
  echo "Configuring parser3..."
  ./configure --prefix=$install_directory \
     "--with-sendmail=$sendmail_command" \
     --with-static-gc=$project_directory/gc/lib \
#     --disable-safe-mode \
#     --with-dynamic-stdcpp \
     --silent
fi
echo "Building parser3..."
make install
echo "DONE"

echo
echo
echo "********************************************************************************************************"
echo "Now you can copy $install_directory with subdirectories"
echo "  -Parser3 WITHOUT XML support-"
echo "to your cgi-bin directory"
echo "Read more about installing Parser here:"
echo "  http://www.parser.ru/en/docs/lang/install4apachecgi.htm in English"
echo "  http://www.parser.ru/docs/lang/install4apachecgi.htm in Russian"
echo "********************************************************************************************************"
