#!/bin/sh

# $Id: buildall-with-xml,v 1.5 2007/02/03 18:15:22 misha Exp $

install_directory=$HOME/parser3install
sendmail_command="/usr/sbin/sendmail -i -t -f postmaster"

echo "buildall-with-xml"
echo "Script author: Alexander Petrosian <paf@design.ru> (http://paf.design.ru)"
echo
echo "Building..."

parser3_directory=`pwd`
cd ..
project_directory=`pwd`
mkdir src >/dev/null 2>&1

if test ! -f "$project_directory/gc/lib/libgc.a"; then
  cd $project_directory/src
  echo "Downloading libgc [1 lib of 3]..."
  wget -c http://www.hpl.hp.com/personal/Hans_Boehm/gc/gc_source/gc6.6.tar.gz
  echo "Unpacking..."
  gunzip -c gc6.6.tar.gz | tar vxf - >/dev/null
  cd gc6.6
  echo "Configuring libgc..."
  CPPFLAGS="-DUSE_LIBC_PRIVATES -DUSE_MMAP -DUSE_MUNMAP" \
  ./configure --prefix=$project_directory/gc --disable-threads --disable-shared --silent
  echo "Building libgc..."
  make
  make install
fi


if test ! -f "$project_directory/gnome/lib/libxml2.a"; then
  cd $project_directory/src
  echo "Downloading libxml [2 lib of 3]..."
  wget -c --passive-ftp ftp://xmlsoft.org/libxml2/libxml2-2.6.27.tar.gz
  echo "Unpacking... (be patient)"
  gunzip -c libxml2-2.6.27.tar.gz | tar vxf - >/dev/null
  cd libxml2-2.6.27
  #sax1, output, tree, xinclude[in libxslt], html[in libxslt, mode=html?] xptr[xinclude]-- needed!
  echo "Configuring libxml..."
  ./configure --prefix=$project_directory/gnome \
    --without-iconv --without-threads --without-debug \
    --without-iso8859x --without-legacy \
    --without-pattern --without-push --without-python \
    --without-reader --without-writer --without-readline --without-regexps \
    --without-schemas --without-schematron \
    --without-modules \
    --without-zlib \
    --disable-shared --silent
  echo "int main(){return 0;}">testapi.c
  echo "int main(){return 0;}">runtest.c
  echo "Building libxml..."
  make
  make install
fi

if test ! -f "$project_directory/gnome/lib/libxslt.a"; then
  cd $project_directory/src
  echo "Downloading libxslt [3 lib of 3]..."
  wget -c --passive-ftp ftp://xmlsoft.org/libxslt/libxslt-1.1.20.tar.gz
  echo "Unpacking... (be patient)"
  gunzip -c libxslt-1.1.20.tar.gz | tar vxf - >/dev/null
  cd libxslt-1.1.20
  echo "Configuring libxslt..."
  ./configure --prefix=$project_directory/gnome \
     --with-libxml-prefix=$project_directory/gnome \
     --without-debug --without-debugger --without-crypto --without-plugins --disable-shared  --silent
  echo "Building libxslt..."
  make
  make install
fi

cd $parser3_directory

if test ! -f "Makefile"; then
  echo "Configuring parser3..."
  ./configure --prefix=$install_directory \
     "--with-sendmail=$sendmail_command" \
     --with-static-gc=$project_directory/gc/lib \
     --with-static-xml=$project_directory/gnome \
     --silent
fi
echo "Building parser3..."
make install
echo "DONE"

echo
echo
echo "********************************************************************************************************"
echo "Now you can copy $install_directory with subdirectories"
echo "  -Parser3 with XML support-"
echo "to your cgi-bin directory"
echo "Read more about installing Parser here:"
echo "  http://www.parser.ru/en/docs/lang/install4apachecgi.htm in English"
echo "  http://www.parser.ru/docs/lang/install4apachecgi.htm in Russian"
echo "********************************************************************************************************"
