SET TOOLS=..\..\..\win32tools
SET CLASSES_INC=classes.inc
ECHO /* do not edit. autogenerated by classes.cmd */ > %CLASSES_INC%
ECHO. >> %CLASSES_INC%
%TOOLS%\ls | %TOOLS%\gawk -f classes.awk >> %CLASSES_INC%
