// @test autogenerate this
//warning: no OP

extern Methoded *MForm_create(Pool& pool);  *this+=MForm_create(pool());
extern Methoded *MResponse_create(Pool& pool);  *this+=MResponse_create(pool());


extern Methoded *MTable_create(Pool& pool);  *this+=MTable_create(pool());
extern Methoded *MFile_create(Pool& pool);  *this+=MFile_create(pool());
extern Methoded *MRandom_create(Pool& pool);  *this+=MRandom_create(pool());
extern Methoded *MMail_create(Pool& pool);  *this+=MMail_create(pool());
extern Methoded *MImage_create(Pool& pool);  *this+=MImage_create(pool());

extern Methoded *MString_create(Pool& pool);  *this+=MString_create(pool());
extern Methoded *MDouble_create(Pool& pool);  *this+=MDouble_create(pool());
extern Methoded *MInt_create(Pool& pool);  *this+=MInt_create(pool());
extern Methoded *MUnknown_create(Pool& pool);  *this+=MUnknown_create(pool());
