/*
  $Id: code.h,v 1.1 2001/02/20 18:45:51 paf Exp $
*/

#ifndef CODE_H
#define CODE_H

enum OPCODE {
	OP_STRING,
	OP_CODE_ARRAY,
	OP_WITH_ROOT,	OP_WITH_SELF,	OP_WITH_READ,	OP_WITH_WRITE,
	OP_CONSTRUCT,
	OP_EXPRESSION_EVAL,	OP_MODIFY_EVAL,
	OP_WRITE,
	OP_REPLACE_RESULT,
	OP_GET_ELEMENT,	OP_GET_ELEMENT__WRITE,
	OP_CREATE_EWPOOL,	OP_REDUCE_EWPOOL,
	OP_CREATE_RWPOOL,	OP_REDUCE_RWPOOL,
	OP_GET_METHOD_FRAME,
	OP_CREATE_JUNCTION,
	OP_STORE_PARAM,
	OP_CALL
};

#endif
